### ISSUE TITLE
Comments directly above control structure should match color of control structure

### ISSUE THREAD

**Issue by Muhd** [writeoncereadmany/StructuralSemanticHighlighter#1]
Right now comments above a block of code (presumably for that block) are given a different color than the block, which seems less intuitive than considering it part of the block it describes.

Actual:
```
green (green) {
  // green
  codeforgreenblock;

  // green
  // green
  red (red) {
    // red
    codeforredblock;
  }
}
```

Expected:
```
green (green) {
  // green
  codeforgreenblock;

  // red
  // red
  red (red) {
    // red
    codeforredblock;
  }
}
```

(Great plugin, by the way)

**Comment by writeoncereadmany** [comment]
That's interesting. The highlighter does this for some structures but not others: for classes/methods, it attaches the correct colour, but not structures within methods. I'll look into making this more general.

edit: It turns out I don't do anything special with comments: I simply colour them according to their parent. Looks like the IntelliJ PSI tree generated attaches contiguous comments before a method to that method, as well as any comments between a javadoc and a method to that method. Comments within a method are always children of that method, not the next block of code.

A large part of this plugin is leveraging the PSI, so special-casing for the block case is going to take a little digging into what the tree looks like...

**Comment by writeoncereadmany** [comment]
Turns out it's quite straightforward! If it's in a code block, then highlight the comment based on the highlight of the next non-whitespace element. Otherwise (eg doc comments), colour it in accordance with its parent element.

I've made the change and uploaded it to the plugin repository, just waiting for it to pass moderation.
